const customers = [
  {
    name: 'Carlos',
    lastName: 'Gómez',
    email: 'carlos.gomez@gmail.com',
    phone: 2216765342,
    password: '$2a$10$fGPJEl5Twzz.eySDoWUFpeOgZB6yNlRGpbVltGt5/MBQMgHXGSrFu',
    token: null,
    idRole: 2,
    image: 'image1.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Juan',
    lastName: 'Martínez',
    email: 'juan.martinez@gmail.com',
    phone: 2216765342,
    password: '$2a$10$fGPJEl5Twzz.eySDoWUFpeOgZB6yNlRGpbVltGt5/MBQMgHXGSrFu',
    token: null,
    idRole: 2,
    image: 'image2.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'María',
    lastName: 'Fernández',
    email: 'maria.fernandez@gmail.com',
    phone: 2216765342,
    password: '$2a$10$fGPJEl5Twzz.eySDoWUFpeOgZB6yNlRGpbVltGt5/MBQMgHXGSrFu',
    token: null,
    idRole: 2,
    image: 'image3.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Laura',
    lastName: 'Pérez',
    email: 'laura.perez@gmail.com',
    phone: 2216765342,
    password: '$2a$10$fGPJEl5Twzz.eySDoWUFpeOgZB6yNlRGpbVltGt5/MBQMgHXGSrFu',
    token: null,
    idRole: 2,
    image: 'image4.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const locations = [
  {
    idCustomer: 3,
    country: 'AR',
    province: 'Santa Fe',
    city: 'Rosario',
    address: 'Calle Santa Fe 789',
    comment: 'Casa de 2 pisos, con puerta gris',
  },
  {
    idCustomer: 4,
    country: 'AR',
    province: 'Mendoza',
    city: 'Mendoza',
    address: 'San Martín 101',
    comment: 'Casa de 2 pisos, con puerta gris',
  },
  {
    idCustomer: 5,
    country: 'AR',
    province: 'Salta',
    city: 'Salta',
    address: 'España 202',
    comment: 'Casa de 2 pisos, con puerta gris',
  },
  {
    idCustomer: 6,
    country: 'AR',
    province: 'Tucumán',
    city: 'San Miguel de Tucumán',
    address: 'San Lorenzo 303',
    comment: 'Casa de 2 pisos, con puerta gris',
  },
  {
    idCustomer: null,
    country: 'AR',
    province: 'San Juan',
    city: 'San Juan',
    address: '25 de Mayo 606',
    comment: 'Casa de 2 pisos, con puerta gris',
  },
  {
    idCustomer: null,
    country: 'AR',
    province: 'La Pampa',
    city: 'Santa Rosa',
    address: 'Avenida Luro 707',
    comment: 'Casa de 2 pisos, con puerta gris',
  },
  {
    idCustomer: null,
    country: 'AR',
    province: 'Neuquén',
    city: 'Neuquén',
    address: 'Avenida Argentina 808',
    comment: 'Casa de 2 pisos, con puerta gris',
  },
  {
    idCustomer: null,
    country: 'AR',
    province: 'Chubut',
    city: 'Comodoro Rivadavia',
    address: 'Rivadavia 909',
    comment: 'Casa de 2 pisos, con puerta gris',
  },
]

const commerces = [
  {
    name: 'La Pizzería',
    email: 'pizzeria@gmail.com',
    password: '$2a$10$fGPJEl5Twzz.eySDoWUFpeOgZB6yNlRGpbVltGt5/MBQMgHXGSrFu',
    idRole: 1,
    idLocation: 8,
    image: 'pizzeria.jpg',
    coverImage: 'coverImage.jpg',
    phone: 1134562789,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'El Rincón Mexicano',
    email: 'rincon.mexicano@gmail.com',
    password: '$2a$10$fGPJEl5Twzz.eySDoWUFpeOgZB6yNlRGpbVltGt5/MBQMgHXGSrFu',
    idRole: 1,
    idLocation: 5,
    image: 'mexicano.jpg',
    coverImage: 'coverImage.jpg',
    phone: 1134562789,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Sushi House',
    email: 'sushi.house@gmail.com',
    password: '$2a$10$fGPJEl5Twzz.eySDoWUFpeOgZB6yNlRGpbVltGt5/MBQMgHXGSrFu',
    idRole: 1,
    idLocation: 6,
    image: 'sushi.jpg',
    coverImage: 'coverImage.jpg',
    phone: 1134562789,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Panadería Delicias',
    email: 'panaderia.delicias@gmail.com',
    password: '$2a$10$fGPJEl5Twzz.eySDoWUFpeOgZB6yNlRGpbVltGt5/MBQMgHXGSrFu',
    idRole: 1,
    idLocation: 7,
    image: 'panaderia.jpg',
    coverImage: 'coverImage.jpg',
    phone: 1134562789,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const products = [
  {
    name: 'Pizza Margherita',
    idCategory: 1,
    idCommerce: 3,
    description: 'Pizza con tomate, mozzarella y albahaca.',
    price: 12,
    available: 20,
    image: '03_pizza.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Burrito de Carne',
    idCategory: 2,
    idCommerce: 3,
    description: 'Burrito de carne asada con guacamole.',
    price: 10,
    available: 15,
    image: '03_burrito.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Nigiri de Salmón',
    idCategory: 3,
    idCommerce: 3,
    description: 'Nigiri de salmón fresco sobre arroz.',
    price: 8,
    available: 30,
    image: '03_nigiri.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Croissants',
    idCategory: 4,
    idCommerce: 4,
    description: 'Croissants recién horneados.',
    price: 3,
    available: 50,
    image: '04_croissants.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Choripán',
    idCategory: 5,
    idCommerce: 4,
    description: 'Choripán con chimichurri.',
    price: 6,
    available: 25,
    image: '04_choripan.jpg',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

const favorites = [
  { idCustomer: 3, idCommerce: 4 },
  { idCustomer: 3, idCommerce: 4 },
  { idCustomer: 4, idCommerce: 3 },
  { idCustomer: 4, idCommerce: 3 },
  { idCustomer: 5, idCommerce: 2 },
  { idCustomer: 5, idCommerce: 2 },
  { idCustomer: 2, idCommerce: 1 },
  { idCustomer: 2, idCommerce: 1 },
];

const orders = [
  { idCustomer: 3, idCommerce: 3, idState: 3, finalPrice: 40, createdAt: new Date(), updatedAt: new Date() },
  { idCustomer: 4, idCommerce: 3, idState: 1, finalPrice: 30, createdAt: new Date(), updatedAt: new Date() },
  { idCustomer: 5, idCommerce: 2, idState: 2, finalPrice: 55, createdAt: new Date(), updatedAt: new Date() },
  { idCustomer: 4, idCommerce: 2, idState: 3, finalPrice: 60, createdAt: new Date(), updatedAt: new Date() },
  { idCustomer: 3, idCommerce: 2, idState: 1, finalPrice: 45, createdAt: new Date(), updatedAt: new Date() },
  { idCustomer: 6, idCommerce: 4, idState: 2, finalPrice: 50, createdAt: new Date(), updatedAt: new Date() },
  { idCustomer: 2, idCommerce: 4, idState: 3, finalPrice: 65, createdAt: new Date(), updatedAt: new Date() },
  { idCustomer: 3, idCommerce: 4, idState: 1, finalPrice: 70, createdAt: new Date(), updatedAt: new Date() },
  { idCustomer: 3, idCommerce: 5, idState: 2, finalPrice: 80, createdAt: new Date(), updatedAt: new Date() },
  { idCustomer: 4, idCommerce: 5, idState: 3, finalPrice: 75, createdAt: new Date(), updatedAt: new Date() },
];

const categoryCommerces = [
  { idCategory: 1, idCommerce: 2 }, { idCategory: 2, idCommerce: 3 },
  { idCategory: 3, idCommerce: 4 }, { idCategory: 4, idCommerce: 5 },
  { idCategory: 9, idCommerce: 2 }, { idCategory: 10, idCommerce: 3 },
  { idCategory: 11, idCommerce: 4 }, { idCategory: 12, idCommerce: 5 },
  { idCategory: 17, idCommerce: 2 }, { idCategory: 18, idCommerce: 3 },
  { idCategory: 19, idCommerce: 4 },
];


module.exports = { customers, locations, commerces, products, favorites, orders, categoryCommerces  };  