-- MySQL Script generated by MySQL Workbench
-- Fri Apr 26 16:28:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flashfood
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `flashfood` ;

-- -----------------------------------------------------
-- Schema flashfood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flashfood` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `flashfood` ;

-- -----------------------------------------------------
-- Table `flashfood`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`categories` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`roles` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`customers` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `lastName` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `phone` BIGINT NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `idRole` INT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idRole` (`idRole` ASC) VISIBLE,
  CONSTRAINT `customers_ibfk_1`
    FOREIGN KEY (`idRole`)
    REFERENCES `flashfood`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`locations` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCustomer` INT NULL DEFAULT NULL,
  `country` VARCHAR(255) NULL DEFAULT NULL,
  `province` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `address` TEXT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCustomer` (`idCustomer` ASC) VISIBLE,
  CONSTRAINT `locations_ibfk_1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `flashfood`.`customers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`commerces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`commerces` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`commerces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `idRole` INT NOT NULL,
  `idLocation` INT NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `coverImage` VARCHAR(255) NULL DEFAULT NULL,
  `phone` BIGINT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idRole` (`idRole` ASC) VISIBLE,
  INDEX `idLocation` (`idLocation` ASC) VISIBLE,
  CONSTRAINT `commerces_ibfk_1`
    FOREIGN KEY (`idRole`)
    REFERENCES `flashfood`.`roles` (`id`),
  CONSTRAINT `commerces_ibfk_2`
    FOREIGN KEY (`idLocation`)
    REFERENCES `flashfood`.`locations` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`categorycommerces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`categorycommerces` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`categorycommerces` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCategory` INT NULL DEFAULT NULL,
  `idCommerce` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCategory` (`idCategory` ASC) VISIBLE,
  INDEX `idCommerce` (`idCommerce` ASC) VISIBLE,
  CONSTRAINT `categorycommerces_ibfk_1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `flashfood`.`categories` (`id`),
  CONSTRAINT `categorycommerces_ibfk_2`
    FOREIGN KEY (`idCommerce`)
    REFERENCES `flashfood`.`commerces` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`days`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`days` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`days` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`favorites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`favorites` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`favorites` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCustomer` INT NULL DEFAULT NULL,
  `idCommerce` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCustomer` (`idCustomer` ASC) VISIBLE,
  INDEX `idCommerce` (`idCommerce` ASC) VISIBLE,
  CONSTRAINT `favorites_ibfk_1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `flashfood`.`customers` (`id`),
  CONSTRAINT `favorites_ibfk_2`
    FOREIGN KEY (`idCommerce`)
    REFERENCES `flashfood`.`commerces` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`states`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`states` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`states` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`orders` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCustomer` INT NOT NULL,
  `idCommerce` INT NOT NULL,
  `idState` INT NULL DEFAULT NULL,
  `finalPrice` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCustomer` (`idCustomer` ASC) VISIBLE,
  INDEX `idCommerce` (`idCommerce` ASC) VISIBLE,
  INDEX `idState` (`idState` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `flashfood`.`customers` (`id`),
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`idCommerce`)
    REFERENCES `flashfood`.`commerces` (`id`),
  CONSTRAINT `orders_ibfk_3`
    FOREIGN KEY (`idState`)
    REFERENCES `flashfood`.`states` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`products` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `idCategory` INT NULL DEFAULT NULL,
  `idCommerce` INT NOT NULL,
  `description` TEXT NOT NULL,
  `price` INT NULL DEFAULT NULL,
  `available` INT NULL DEFAULT NULL,
  `image` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCategory` (`idCategory` ASC) VISIBLE,
  INDEX `idCommerce` (`idCommerce` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `flashfood`.`categories` (`id`),
  CONSTRAINT `products_ibfk_2`
    FOREIGN KEY (`idCommerce`)
    REFERENCES `flashfood`.`commerces` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`orderdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`orderdetails` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`orderdetails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idOrder` INT NULL DEFAULT NULL,
  `idProduct` INT NULL DEFAULT NULL,
  `quantity` INT NULL DEFAULT NULL,
  `unitPrice` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idOrder` (`idOrder` ASC) VISIBLE,
  INDEX `idProduct` (`idProduct` ASC) VISIBLE,
  CONSTRAINT `orderdetails_ibfk_1`
    FOREIGN KEY (`idOrder`)
    REFERENCES `flashfood`.`orders` (`id`),
  CONSTRAINT `orderdetails_ibfk_2`
    FOREIGN KEY (`idProduct`)
    REFERENCES `flashfood`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`reviews`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`reviews` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`reviews` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idCustomer` INT NULL DEFAULT NULL,
  `idCommerce` INT NULL DEFAULT NULL,
  `comment` TEXT NULL DEFAULT NULL,
  `score` INT NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCustomer` (`idCustomer` ASC) VISIBLE,
  INDEX `idCommerce` (`idCommerce` ASC) VISIBLE,
  CONSTRAINT `reviews_ibfk_1`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `flashfood`.`customers` (`id`),
  CONSTRAINT `reviews_ibfk_2`
    FOREIGN KEY (`idCommerce`)
    REFERENCES `flashfood`.`commerces` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`schedules`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`schedules` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`schedules` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idDay` INT NULL DEFAULT NULL,
  `idCommerce` INT NULL DEFAULT NULL,
  `open` TINYINT(1) NULL DEFAULT NULL,
  `opening` TIME NULL DEFAULT NULL,
  `close` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idDay` (`idDay` ASC) VISIBLE,
  INDEX `idCommerce` (`idCommerce` ASC) VISIBLE,
  CONSTRAINT `schedules_ibfk_1`
    FOREIGN KEY (`idDay`)
    REFERENCES `flashfood`.`days` (`id`),
  CONSTRAINT `schedules_ibfk_2`
    FOREIGN KEY (`idCommerce`)
    REFERENCES `flashfood`.`commerces` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `flashfood`.`sequelizemeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `flashfood`.`sequelizemeta` ;

CREATE TABLE IF NOT EXISTS `flashfood`.`sequelizemeta` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
